services:
  - type: web
    name: neuralwired
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 16
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
