baseURL = "https://rulercosta.github.io/"
languageCode = "en-us"
title = "cryptoknights"

# Control content summary length
summaryLength = 30

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

# Ensure proper MIME types for CSS
[mediaTypes]
  [mediaTypes."text/css"]
    suffixes = ["css"]

[outputFormats]
  [outputFormats.CSS]
    mediaType = "text/css"
    isPlainText = false
    isHTML = false

# Default static file configuration
[server]
  [[server.headers]]
    for = "/**/*.css"
    [server.headers.values]
      Content-Type = "text/css"

[params]
  description = "cryptoknights blog - thoughts and ideas"
  author = "rulercosta"
    
  # Excerpt length - controls default truncation
  excerptLength = 100
  
  # Social links (used in footer)
  github = "https://github.com/rulercosta"
  linkedin = "https://linkedin.com/in/anubhav03111"
  twitter = "https://twitter.com/rulercostax"
